### ISSUE TITLE
 RuntimeError: Error(s) in loading state_dict for YOLOX

### ISSUE THREAD

**Issue by huaq000001** [HuYo-OS/Genshin_auto_fish#30]
### 复现步骤 | Steps to Reproduce

1.使用作者提供的best_tiny3.pth模型权重大小不匹配
2.大佬救救
3.

### 预期行为 | Expected Behavior

😀

### 实际行为 | Actual Behavior

😫

### 日志 | Logs

<details>

```

(ysfish) C:\Users\86182\Genshin_auto_fish>python fishing.py --device gpu

    ██████╗ ███████╗███╗   ██╗███████╗██╗  ██╗██╗███╗   ██╗
   ██╔════╝ ██╔════╝████╗  ██║██╔════╝██║  ██║██║████╗  ██║
   ██║  ███╗█████╗  ██╔██╗ ██║███████╗███████║██║██╔██╗ ██║
   ██║   ██║██╔══╝  ██║╚██╗██║╚════██║██╔══██║██║██║╚██╗██║
   ╚██████╔╝███████╗██║ ╚████║███████║██║  ██║██║██║ ╚████║
    ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
 █████╗ ██╗   ██╗████████╗ ██████╗ ███████╗██╗███████╗██╗  ██╗
██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔════╝██║██╔════╝██║  ██║
███████║██║   ██║   ██║   ██║   ██║█████╗  ██║███████╗███████║
██╔══██║██║   ██║   ██║   ██║   ██║██╔══╝  ██║╚════██║██╔══██║
██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║     ██║███████║██║  ██║
╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝

检测到 原神 已最小化，已自动处理
当前游戏分辨率为：2559 x 1599
Traceback (most recent call last):
  File "C:\Users\86182\Genshin_auto_fish\fishing.py", line 210, in <module>
    main(exp, args)
  File "C:\Users\86182\Genshin_auto_fish\fishing.py", line 117, in main
    model.load_state_dict(ckpt["model"])
  File "C:\Users\86182\.conda\envs\ysfish\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([7, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([9]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([7, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([9]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([7, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([9]).

```
</details>

**Comment by huaq000001** [comment]
finish
