### ISSUE TITLE
[问题] 目前存在的问题

### ISSUE THREAD

**Issue by LittleMio** [HuYo-OS/Genshin_auto_fish#31]
### 在这里简单概括一下目前存在的问题

- [x] 1.目前存在游戏全屏时获取到的分辨率的W，H与实际分辨率的W, H差1 
- [ ] 2.选取鱼饵的操作部分仍有一点问题
- [ ] 3.由于个人忙于学业，目前没有多少精力收集图像用来训练，所以收集到的图片也比较少，训练出来的效果也不太理想

**Comment by kxgx** [comment]
Traceback (most recent call last):
  File "C:\Windows\System32\Genshin_auto_fish\fishing.py", line 210, in <module>
    main(exp, args)
  File "C:\Windows\System32\Genshin_auto_fish\fishing.py", line 117, in main
    model.load_state_dict(ckpt["model"])
  File "C:\ProgramData\anaconda3\envs\ysfish\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([6, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([9]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([6, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([9]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([6, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([9]).
请问这个报错有解决方法吗

**Comment by LittleMio** [comment]
> Traceback (most recent call last):
>   File "C:\Windows\System32\Genshin_auto_fish\fishing.py", line 210, in <module>
>     main(exp, args)
>   File "C:\Windows\System32\Genshin_auto_fish\fishing.py", line 117, in main
>     model.load_state_dict(ckpt["model"])
>   File "C:\ProgramData\anaconda3\envs\ysfish\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for YOLOX:
>         size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([6, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
>         size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([9]).
>         size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([6, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
>         size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([9]).
>         size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([6, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 96, 1, 1]).
>         size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([9]).
> 请问这个报错有解决方法吗

更新到最新代码，并使用预发行的模型
[https://github.com/HuYo-OS/Genshin_auto_fish/releases/tag/v1.0-beta.1](https://github.com/HuYo-OS/Genshin_auto_fish/releases/tag/v1.0-beta.1)

**Comment by soondro2266** [comment]
HWND hWnd = FindHandle("YuanShen.exe");
at src/screenshot.cpp Line 23
其他區的handle有可能是GenshinImpact.exe
像我就會直接跳Fisher: Fatal screenshot error: the game handle is NULL! The fisher has automatically stopped.
有甚麼方法可以解決嗎，我也無法直接運行source code.
