### ISSUE TITLE
[错误] 按照readme进行部署完成后，启动会报错，无法启动。

### ISSUE THREAD

**Issue by WuMing-YQ** [HuYo-OS/Genshin_auto_fish#34]
### 复现步骤 | Steps to Reproduce

系统是windows11 22h3，anaconda环境，两次都按照readme中的步骤部署的。是否是我哪里做错了，能否指明一下，非常感谢。

### 预期行为 | Expected Behavior

正常启动到init

### 实际行为 | Actual Behavior

一开始报错没找到库：pydantic。于是我就执行了pip install pydantic==1.9.0
然后再执行启动代码，结果报告是：
``` "load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "C:\Users\Qing\Genshin_auto_fish\utils\tools.py", line 17

    return yaml.load(path.read_text(encoding=encoding),

### 日志 | Logs

``` (ysfish) C:\Users\Qing\Genshin_auto_fish>python fishing.py --device gpu
Traceback (most recent call last):
  File "C:\Users\Qing\Genshin_auto_fish\fishing.py", line 19, in <module>
    from utils.config import config, logger
  File "C:\Users\Qing\Genshin_auto_fish\utils\__init__.py", line 1, in <module>
    from .utils import *
  File "C:\Users\Qing\Genshin_auto_fish\utils\utils.py", line 7, in <module>
    from utils.config import MONITOR_HEIGHT, MONITOR_WIDTH, config
  File "C:\Users\Qing\Genshin_auto_fish\utils\config.py", line 36, in <module>
    class FishConfigManager:
  File "C:\Users\Qing\Genshin_auto_fish\utils\config.py", line 38, in FishConfigManager
    config = ConfigModel.parse_obj(load_yaml(FISH_CONFIG))
  File "C:\Users\Qing\Genshin_auto_fish\utils\tools.py", line 17, in load_yaml
    return yaml.load(path.read_text(encoding=encoding),
  File "C:\Users\Qing\.conda\envs\ysfish\lib\site-packages\ruamel\yaml\main.py", line 1085, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "C:\Users\Qing\.conda\envs\ysfish\lib\site-packages\ruamel\yaml\main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError:
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "C:\Users\Qing\Genshin_auto_fish\utils\tools.py", line 17

    return yaml.load(path.read_text(encoding=encoding),

**Comment by WuMing-YQ** [comment]
而后，我尝试执行`pip install ruamel.yaml==0.16.11`后再次运行。出现了如下的报错：
``` (ysfish) C:\Users\Qing\Genshin_auto_fish>python fishing.py --device gpu
Traceback (most recent call last):
  File "pydantic\main.py", line 507, in pydantic.main.BaseModel.parse_obj
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Qing\Genshin_auto_fish\fishing.py", line 19, in <module>
    from utils.config import config, logger
  File "C:\Users\Qing\Genshin_auto_fish\utils\__init__.py", line 1, in <module>
    from .utils import *
  File "C:\Users\Qing\Genshin_auto_fish\utils\utils.py", line 7, in <module>
    from utils.config import MONITOR_HEIGHT, MONITOR_WIDTH, config
  File "C:\Users\Qing\Genshin_auto_fish\utils\config.py", line 36, in <module>
    class FishConfigManager:
  File "C:\Users\Qing\Genshin_auto_fish\utils\config.py", line 38, in FishConfigManager
    config = ConfigModel.parse_obj(load_yaml(FISH_CONFIG))
  File "pydantic\main.py", line 510, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for ConfigModel
__root__
  ConfigModel expected dict not NoneType (type=type_error)

**Comment by LittleMio** [comment]
请提供python的version和python软件包列表

**Comment by WuMing-YQ** [comment]
> 请提供python的version和python软件包列表

如果是windows的cmd下输入`python --version` 返回是3.12.0
在anaconda中输入`python --version` 返回是3.10.13
（没学过python不清楚windows的版本会不会影响anaconda环境中python的版本，所以一起发了）

同样在anaconda中执行的`pip list` 返回如下
``` certifi            2023.11.17
charset-normalizer 3.3.2
colorama           0.4.6
contourpy          1.2.0
cycler             0.12.1
filelock           3.13.1
fonttools          4.45.1
fsspec             2023.10.0
idna               3.4
Jinja2             3.1.2
keyboard           0.13.5
kiwisolver         1.4.5
loguru             0.6.0
MarkupSafe         2.1.3
matplotlib         3.6.3
MouseInfo          0.1.3
mpmath             1.3.0
networkx           3.2.1
numpy              1.23.5
opencv-python      4.7.0.68
packaging          23.2
Pillow             10.1.0
pip                23.3.1
PyAutoGUI          0.9.53
pycocotools        2.0.6
pydantic           1.9.0
PyGetWindow        0.0.9
PyMsgBox           1.0.9
pyparsing          3.1.1
pyperclip          1.8.2
PyRect             0.2.0
PyScreeze          0.1.30
python-dateutil    2.8.2
pytweening         1.0.7
pywin32            305
requests           2.31.0
ruamel.yaml        0.16.11
ruamel.yaml.clib   0.2.8
setuptools         68.0.0
six                1.16.0
sympy              1.12
tabulate           0.9.0
thop               0.1.1.post2209072238
torch              2.1.1
torchaudio         2.1.1
torchvision        0.16.1
tqdm               4.64.1
typing_extensions  4.8.0
urllib3            2.1.0
wheel              0.41.2
win32-setctime     1.1.0

**Comment by LittleMio** [comment]
经复现，问题出现在之前安装的ruamel.yaml版本过高，导致生成了空的配置文件**config.yaml**，你可以把根目录下的**config.yaml**删除，然后重新运行

**Comment by WuMing-YQ** [comment]
> 经复现，问题出现在之前安装的ruamel.yaml版本过高，导致生成了空的配置文件**config.yaml**，你可以把根目录下的**config.yaml**删除，然后重新运行

感谢，问题解决了，现在可以初始化并且运行了。
